version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -extldflags '-static'

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "terraform-provider-tigris_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
