version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -extldflags '-static'

archives:
  - format: zip
    name_template: "terraform-provider-tigris_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "terraform-provider-tigris_{{ .Version }}_SHA256SUMS"
  extra_files:
    - glob: "terraform-registry-manifest.json"
      name_template: "terraform-provider-tigris_{{ .Version }}_manifest.json"
  algorithm: sha256
release:
  extra_files:
    - glob: "terraform-registry-manifest.json"
      name_template: "terraform-provider-tigris_{{ .Version }}_manifest.json"
